name: Validation
on:
  - push
  - pull_request
jobs:
  test:
    name: Test-Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: dschep/install-pipenv-action@v1
      - name: Setup pipenv
        run: |
          pipenv install --dev
      - name: Run unittests/coverage
        run: |
          pipenv run tests
          pipenv run cov | tee report.txt
          exit $?
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v1
        with:
          name: coverage_report
          path: report.txt
